version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-service-account.json
      - PORT=8000
      - ENV=production
    restart: unless-stopped 